django-flashcard-master/django-flashcard-master/flashcard/urls.py
from django.conf.urls import url
from . import views

app_name = 'flashcard'

urlpatterns = [
    # /
    url(r'^flashcard/?$',                            views.index,    name='index'),
    # /flashcard/create
    url(r'^flashcard/create/?$',                     views.create_set, name='create'),
    # /flashcard/112
    url(r'^flashcard/(?P<set_id>[0-9]+)(:show)?/?$', views.show_set, name='show'),
    # /flashcard/112:edit
    url(r'^flashcard/(?P<set_id>[0-9]+)/edit/?$',    views.edit_set, name='edit'),
    # /flashcard/112:save
    url(r'^flashcard/(?P<set_id>[0-9]+)/save/create=(?P<create>[0-9]+)/?$',  views.save_set, name='save'),
    # /flashcard/112/learn
    url(r'^flashcard/(?P<set_id>[0-9]+)/learn/?$', views.learn, name='learn'),
    # /flashcard/112/flip
    url(r'^flashcard/(?P<set_id>[0-9]+)/flip/?$', views.flip, name='flip'),
    # /flashcard/112/export
    url(r'^flashcard/(?P<set_id>[0-9]+)/export/?$', views.export, name='export'),
]

django-flashcard-master/django-flashcard-master/flashcard/models.py
from django.db import models


class Set(models.Model):
    name = models.CharField(max_length=128)
    color = models.CharField(max_length=7, default='f5f5dc')

    def __str__(self):
        return self.name


class Card(models.Model):
    set = models.ForeignKey(Set, on_delete=models.CASCADE)
    front = models.CharField(max_length=256)
    back = models.CharField(max_length=256)

    def __str__(self):
        return "(" + self.front + ", " +  self.back + ")"

django-flashcard-master/django-flashcard-master/flashcard/forms.py
from django import forms

from .models import Set, Card
from random import randrange


class SetForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput, label='')
    color = forms.CharField(widget=forms.TextInput, label='')

    class Meta:
        model = Set
        fields = ['name']


class CardForm(forms.ModelForm):
    front = forms.CharField(widget=forms.TextInput, label='')
    back = forms.CharField(widget=forms.TextInput, label='')

    class Meta:
        model = Card
        fields = ['front', 'back']

django-flashcard-master/django-flashcard-master/flashcard/views.py
from .models import Set, Card
from django.shortcuts import render
from .forms import CardForm, SetForm
from django.forms import formset_factory
from django.core import serializers
from random import randrange
from django.http import HttpResponse


all_sets = {}
current_cards = {}
current_set_id = -1
empty_card_index = 0
admin = False

# Showing the page
def index(request):
    global all_sets
    all_sets = Set.objects.all()
    set_lens = []
    for set in all_sets:
        # Subtract one from the length for the empty card.
        set_lens.append(len(set.card_set.all()) - 1)

    return render(request, 'flashcard/index.html', {'all_sets' : all_sets, 'set_lens': set_lens, 'admin': admin})

# Flashcard set page
def show_set(request, set_id):
    global all_sets, current_cards, current_set_id
    set = Set.objects.get(id=set_id)
    current_cards = set.card_set.all()
    title = set.name

    current_set_id = set_id

    return render(request, 'flashcard/set.html', {
        'set_id': set_id, 'cards': current_cards, 'title': title, 'empty_card_index': 0, 'color': set.color, 'admin': admin
    })


def create_set(request):
    if admin is False:
        return HttpResponse('')

    def random_color():
        color = '%x' % randrange(16777215)
        c_len = len(color)
        if c_len < 6:
            color = '0' * (6- c_len) + color

        return color

    card_form_set = formset_factory(CardForm)

    # set_id set to 0 so save_set() will know that the set is brand new
    set_id = 0
    initial_data = {
        'form-TOTAL_FORMS': 6,
        'form-INITIAL_FORMS': 0,
        'form-MAX_FORMS': '',
        'form-0-front': '',
        'form-0-back': '',
    }

    formset = card_form_set(initial_data)
    color = random_color()
    title_form = SetForm(initial={'name': '', 'color': color})

    return render(request, 'flashcard/edit.html', {
        'cards': current_cards, 'set_id': set_id, 'title_form': title_form, 'formset': formset,
        'empty_card_index': empty_card_index, 'create': 1, 'color': color, 'admin': admin
    })


def edit_set(request, set_id):
    global current_set_id
    if admin is False:
        return HttpResponse('')

    set = Set.objects.get(id=set_id)
    current_cards = set.card_set.all()
    card_form_set = formset_factory(CardForm)

    initial_data = {
        'form-TOTAL_FORMS': len(current_cards),
        'form-INITIAL_FORMS': len(current_cards),
        'form-MAX_NUM_FORMS': '',
        'form-0-front': '',
        'form-0-back': '',
    }

    for i in range(1, initial_data['form-TOTAL_FORMS']):
        front_string = 'form-' + str(i) + '-front'
        back_string = 'form-' + str(i) + '-back'
        initial_data[front_string] = current_cards[i].front
        initial_data[back_string] = current_cards[i].back

    formset = card_form_set(initial_data)
    title_form = SetForm(initial={'name': Set.objects.get(id=set_id).name, 'color': set.color})
    # formset.is_valid()
    return render(request, 'flashcard/edit.html', {
        'set_id': current_set_id, 'title_form': title_form, 'formset': formset,
        'empty_card_index': empty_card_index, 'create': 0, 'color': set.color, 'admin': admin
    })


def save_set(request, set_id, create):
    if request.method == 'POST':
        print("Create: ", type(create))
        # Check if create is 1 (create new set) or a 0 (edit an old set)
        if int(create):
            flashcards_data = Set.objects.create(
                name=request.POST['name'],
                color=request.POST['color'][1:]     # Removing the '#' from the beginning of the hex
            )
            set_id = flashcards_data.id

        else:
            print('Dropping old set')
            flashcards_data = Set.objects.get(id=set_id)
            flashcards_data.name = request.POST['name']
            flashcards_data.color = request.POST['color'][1:]   # Removing the '#' from the beginning of the hex
            flashcards_data.save()
            flashcards = flashcards_data.card_set.all()
            flashcards.delete()

        Card.objects.create(
            set_id=set_id,
            front='',
            back=''
        )
        print(flashcards_data.card_set.all())

        i = 1
        while True:
            print(i)
            form_front_string = 'form-' + str(i) + '-front'
            form_back_string = 'form-' + str(i) + '-back'
            if form_front_string not in request.POST or form_back_string not in request.POST:
                break

            if request.POST[form_front_string] != '' and request.POST[form_back_string] != '':
                Card.objects.create(
                    set_id=set_id,
                    front=request.POST[form_front_string],
                    back=request.POST[form_back_string],
                )

            i += 1

    return show_set(request, set_id)


def flip(request, set_id):
    flashcards = serializers.serialize("json", Set.objects.get(id=set_id).card_set.all())
    return render(request, 'flashcard/flip.html', {
        'cards': flashcards, 'set_id': set_id, 'admin': admin
    })


def learn(request, set_id):
    flashcards_data = Set.objects.get(id=set_id)
    flashcards = serializers.serialize("json", flashcards_data.card_set.all())
    return render(request, 'flashcard/learn.html', {
        'title': flashcards_data.name, 'cards': flashcards, 'set_id': set_id, 'admin': admin
    })


def export(request, set_id):
    flashcards_data = Set.objects.get(id=set_id)
    flashcards = flashcards_data.card_set.all()
    return render(request, 'flashcard/export.html', {
        'title': flashcards_data.name, 'cards': flashcards[1:], 'set_id': set_id, 'admin': admin
    })

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/back_root_template.html
{% extends 'flashcard/root_template.html' %}

{% block body %}
    <nav class="navbar navbar-default">
      <div id="navbar-container" class="container-fluid">

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li><a href="#" onclick="history.go(-1)" class="">Go Back</a></li>
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/edit.html
{%  extends 'flashcard/root_template.html' %}

{% block body %}
    <div class="container">
        <style>
            #id_color {
                background-color: #{{ color }};
            }
        </style>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'flashcard:save' set_id create %}" method="post">
            {% csrf_token %}
            <div id="set-title">
                <span>{{ title_form }}</span>
                <script>
                    $('#id_color').val("#" + $('#id_color').val());
                </script>
            </a>
            </div>

            <table id="set-formset" class="table">
                    <thead id="card-cols">
                        <th></th>
                        <th>Terms</th>
                        <th>Definitions</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% with formset|length as formset_length %}
                            {{ formset.management_form }}
                            {% for form in formset %}
                                <tr id="card-{{ forloop.counter0 }}" class="card">
                                    <td class="counter">{{ forloop.counter0 }}</td>
                                    <td class="card-front">{{ form.front }}</td>
                                    <td class="card-back">{{ form.back }}</td>
                                    <td class="delete-card-btn">x</td>
                                </tr>
                                {% if forloop.counter == formset_length %}
                                    <script>window.onload=function() { setCardCounter({{ formloop.counter0 }}); }</script>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    </tbody>
                </table>
                <script>window.onload=function() { setEmptyCard({{ empty_card_index}}); }</script>
            </table>

            <textarea id="set-import" rows="10" cols="100" style="display: none"></textarea>

        <div class="row container">
            <a id="addCard-btn" class="btn btn-default btn-md" onclick="newCard()">Add Card</a>
            <a id="import-btn" class="btn btn-default btn-md" onclick="showImport()">Import</a>
            <a id="import-save-btn" class="btn btn-default btn-md" style="display: none" onclick="saveImport()">Save</a>

            <input id="done-btn" class="btn btn-default btn-md" style="float: right" type="submit" value="Done"/>
        </div>

        </form>
        <script>
            function showImport() {
                $('#set-formset').hide();
                $('#addCard-btn').hide();
                $('#import-btn').hide();
                $('#done-btn').hide();
                $('#import-save-btn').show();
                $('#set-import').show();

            }

            function showFormset() {
                $('#import-save-btn').hide();
                $('#set-import').hide();
                $('#set-formset').show();
                $('#addCard-btn').show();
                $('#import-btn').show();
                $('#done-btn').show();

            }

            function saveImport() {
                showFormset();

                var rows = $('#set-import').val().split('\n');
                console.log("rows: " + rows.length);
                var cards = $('.card');
                var card_length = cards.length;
                console.log("card-length: " + card_length);

                // If cards need to be created
                if (card_length - 1 < rows.length) {
                    for (var i = 0; i <= rows.length - card_length; i++) {
                        newCard();
                    }
                } else {
                    for (var i = card_length - 1; i > rows.length;i--) {
                        cards[i].remove();
                    }

                }

                console.log("adding data to cards");
                for(var i = 1; i <= rows.length; i++) {
                    console.log(i);
                    var front = rows[i - 1].split(',')[0].trim();
                    var back = rows[i - 1].split(',')[1].trim();
                    $('#id_form-' + i + '-front').eq(0).val(front);
                    $('#id_form-' + i + '-back').eq(0).val(back);
                }

            }
        </script>
    </div>

{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/export.html
{%  extends 'flashcard/root_template.html' %}

{% block body %}

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <div class="container">
        <div id="set-title">
        <span id="id_name">Export {{ title }}</span>
    </div>

        <div class="row container">
            <form action="">
    {#            <div><input id="csv-btn" type="radio" name="file-type" value="CSV" checked="checked"> CSV</div>#}
    {#            <div><input id="tsv-btn" type="radio" name="file-type" value="TSV"> TSV</div>#}
            </form>
     {#  Really dirty indentation below because textarea needed to be spaceless to give proper spacing  #}
        <textarea id="csv" rows="{{ cards|length }}" cols="100">{% spaceless %}
{% for card in cards %}{{ card.front }}, {{ card.back }}
{% endfor %}{% endspaceless %}</textarea>
    {##}
    {#    <textarea id="tsv" rows="{{ cards|length }}" cols="100" style="display: none;">{% spaceless %}#}
    {#{% for card in cards %}{{ card.front }}     {{ card.back }}#}
    {#{% endfor %}{% endspaceless %}</textarea>#}
    {#  End of really dirty indentation  #}
            <div>
                <input id="back-btn" class="btn btn-default btn-md" value="Back"
                   onclick="window.location.href='{% url 'flashcard:show' set_id %}'">
            </div>
        </div>
        <script>
            function updateExport() {
                console.log("Update Export");
                if ($("input[id='csv-btn']").is(':checked')) {
                    $('#tsv').hide();
                    $('#csv').show();
                } else if ($("input[id='tsv-btn']").is(':checked')) {
                    $('#csv').hide();
                    $('#tsv').show();
                }
            }
        </script>
    </div>



{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/flip.html
{% extends 'flashcard/root_template.html' %}
{% load staticfiles %}

{% block body %}
    <style>
        .front {
            position: static;
        }

    .navigation.row {
        margin-top: 1%;
    }

    </style>

    <div class="container">
        <div id="set-title">
            <input id="learn-btn" class="btn btn-default btn-md" value="Learn"
                   onclick="window.location.href='{% url 'flashcard:learn' set_id %}'" >
            <input id="flip-btn" class="btn btn-default btn-md" value="View"
                   onclick="window.location.href='{% url 'flashcard:show' set_id %}'" >
        </div>
    </div>
    <div class="container-fluid">
        <div class="card row">
            <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2
                        col-xs-8 col-sm-8 col-md-8 col-lg-8 card-container">
                <div id="card">
                  <div class="card-side front text-center">
                    <span id="front-content"></span>
                  </div>
                  <div class="card-side back text-center">
                    <span id="back-content"></span>
                  </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="navigation row">
            <div class="col-xs-offset-3 col-sm-offset-3 col-md-offset-3 col-lg-offset-3
                        col-xs-2 col-sm-2 col-md-2 col-lg-2 card-container">
                <div id="left-card">
                  <div class="turn-btn text-center" onclick="prevFlip()">
                      prev
                  </div>
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 card-container">
                <div id="card-index" class="text-center">
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 card-container">
                <div id="right-card">
                  <div class="turn-btn text-center" onclick="nextFlip()">
                      next
                  </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'flashcard/js/flip.js' %}"></script>
    <script>
        window.onload=function() { playFlip({{ cards|safe }}); };

        $(document).ready(function() {
            $(".card-side.front").css('position', 'absolute');
            $(".card-side.back").css('position', 'static');
        });
    </script>
{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/index.html
{%  extends 'flashcard/root_template.html' %}
{% load flashcard_extras %}

{% block body %}
    <div class="container-fluid">
         {% for set in all_sets %}
            <div class="col-sm-12 col-md-6 col-lg-3 card" onclick="location.href='/flashcard/{{ set.id }}/flip';">
                <div>
                  <div class="first front text-center" style="background-color: #{{ set.color }};">
                      <a id="front-content">{{ set.name }}</a>
                  </div>

                  <div class="second front text-center" style="background-color: #{{ set.color }};">
                      <a id="front-content">{{ set.name }}</a>
                  </div>

                  <div class="third front text-center" style="background-color: #{{ set.color }};">
                      <a id="front-content">{{ set.name }}</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/learn.html
{% extends 'flashcard/root_template.html' %}
{% load staticfiles %}

{% block body %}
    <style>
        #word-container, #answer-input {
            font-size: 24px;
        }
        #answer-btn {
            display: inline;
            font-size: 20px;
        }
        #learn-container, #score-container, #result-container, #end-container {
            border-style: solid;
            padding: 1%;
            border-width: 1px;
        }
        #learn-container {
            margin-right: 1%;
        }
        .score-info {
            font-weight: bold;
        }
        #correct-count {
            color: green;
        }
        #incorrect-count {
            color: red;
        }

    </style>
    <div class="container">
          <div id="set-title">
            <span id="id_name">Learn {{ title }}</span>
            <input id="learn-btn" class="btn btn-default btn-md" value="View"
            <input id="learn-btn" class="btn btn-default btn-md" value="View"
                   onclick="window.location.href='{% url 'flashcard:show' set_id %}'" >
            <input id="flip-btn" class="btn btn-default btn-md" value="Flip"
                   onclick="window.location.href='{% url 'flashcard:flip' set_id %}'" >
        </div>
    </div>
    <div class="container">
        <div id="learn-container" class="container col-xs-8 col-sm-8 col-md-8 col-lg-8">
            <div id="word-container">
            </div>
            <div>
                <input id="answer-input">
                <a id="answer-btn" class="btn btn-default" onclick="answerLearn()">Answer</a>
            </div>
        </div>
        <div id="result-container" class="container col-xs-8 col-sm-8 col-md-8 col-lg-8" style="display: none">
            <div id="result" class=" text-center">
                RESULT
            </div>
            <div id="question" class="container">
                Q:
            </div>
            <div id="correct-answer" class="container">
                A:
            </div>
            <span id="next-container">
            </span>
        </div>
        <div id="score-container" class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <p class="score-info">Remaining</p>
            <p id="remaining-count"></p>
            <p class="score-info">Correct</p>
            <p id="correct-count"></p>
            <p class="score-info">Incorrect</p>
            <p id="incorrect-count"></p>
        </div>
        <div id="end-container" class="container col-xs-8 col-sm-8 col-md-8 col-lg-8" style="display: none;">
            <p id="correct-count-end">Correct: </p>
            <p id="incorrect-count-end">Incorrect: </p>
            <p id="info-end"></p>
            <span id="next-container-end"></span>
        </div>
    </div>

    <script src="{% static 'flashcard/js/learn.js' %}"></script>
    <script>
        window.onload=function() { playLearn({{ cards|safe }}); };
    </script>
{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/root_template.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Flashcard</title>

    <link href={%  static "flashcard/css/main.css" %} rel="stylesheet">

     <!-- Bootstrap CSS -->
    <link href={%  static "flashcard/css/bootstrap.min.css" %} rel="stylesheet">

    <!-- jQuery -->
    <script src={% static "flashcard/js/jquery.min.js" %}></script>

    <!-- Bootstrap JavaScript -->
    <script src={% static "flashcard/js/bootstrap.min.js" %}></script>

    <!-- Card Flipping jQuery plug-in -->
    <script src={% static "flashcard/js/jquery.flip.min.js" %}></script>

    <!-- Main -->
    <script src={% static "flashcard/js/main.js" %}></script>
</head>

<body>
<nav class="navbar navbar-default">
  <div id="navbar-container" class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/flashcard">
            Flashcard
        </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
          {% if admin == True %}

        <li><a href="{% url 'flashcard:index' %}" class="btn btn-nav">Your Sets</a></li>
        <li><a href="{% url 'flashcard:create' %}" class="btn btn-nav">Create</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
{#<div class="container">#}
{#    <div class="col-lg-12">#}
        {% block body %}
        {% endblock %}
{#    </div>#}
{#</div>#}

</body>

</html>

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/set.html
{%  extends 'flashcard/root_template.html' %}

{% block body %}
    <div class="container">
          <div id="set-title">
            <span id="id_name">{{ title }}</span>
            <svg width="28" height="28" style="vertical-align: bottom;">
                <rect width="28" height="28" style="fill: #{{  color }}"/>
            </svg>
            <input id="learn-btn" class="btn btn-default btn-md" value="Learn"
                   onclick="window.location.href='{% url 'flashcard:learn' set_id %}'" >
            <input id="flip-btn" class="btn btn-default btn-md" value="Flip"
                   onclick="window.location.href='{% url 'flashcard:flip' set_id %}'" >
        </div>
        <table id="set-list" class="table">
            <thead id="card-cols">
                <th></th>
                 <th>Terms</th>
                <th>Definitions</th>
                <th></th>
            </thead>
            <tbody>
                {% for card in cards %}
                    <tr id="card-{{ forloop.counter0 }}" class="card">
                        <td class="counter">{{ forloop.counter0 }}</td>
                        <td class="card-front">{{ card.front }}</td>
                        <td class="card-back">{{ card.back }}</td>
                        <td></td>
                    </tr>
                {% endfor %}
                <script>window.onload=function() { setEmptyCard({{ empty_card_index}}); }</script>
            </tbody>
        </table>
    {% if admin == True %}

        <input id="edit-btn" class="btn btn-default btn-md" value="Edit"
               onclick="window.location.href='{% url 'flashcard:edit' set_id %}'">
        <input id=export-btn" class="btn btn-default btn-md" value="Export"
               onclick="window.location.href='{% url 'flashcard:export' set_id %}'">
    {% endif %}
    </div>


{% endblock %}

django-flashcard-master/django-flashcard-master/flashcard/templates/flashcard/show.html
{% block body %}
    {% for card in cards %}
        <div class="row list-flashcards">
                <div>
                    <div class="col-lg-6">{{ card.front }}</div>
                    <div class="col-lg-6">{{ card.back }} </div>
                </div>
        </div>
    {% endfor %}
{#    <p href="{% url 'flashcard:edit' set_id %}" class="btn btn-default" id="menu-toggle">Toggle</p>#}
    <form action="% url 'flashcard:edit' set_id %}" method="POST">
        <input id="submit" type="button" value="Edit">
    </form>

{% endblock %}